# Generated by Django 5.0.6 on 2024-06-27 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bebesyniños',
            old_name='peso_producto',
            new_name='peso_volumen_producto',
        ),
        migrations.RenameField(
            model_name='bebidasylicores',
            old_name='peso_producto',
            new_name='peso_volumen_producto',
        ),
        migrations.RenameField(
            model_name='carnes',
            old_name='peso_producto',
            new_name='peso_volumen_producto',
        ),
        migrations.RenameField(
            model_name='congelados',
            old_name='peso_producto',
            new_name='peso_volumen_producto',
        ),
        migrations.RenameField(
            model_name='despensa',
            old_name='peso_producto',
            new_name='peso_volumen_producto',
        ),
        migrations.RenameField(
            model_name='ferreteria',
            old_name='peso_producto',
            new_name='peso_volumen_producto',
        ),
        migrations.RenameField(
            model_name='limpieza',
            old_name='peso_producto',
            new_name='peso_volumen_producto',
        ),
        migrations.RenameField(
            model_name='mascotas',
            old_name='peso_producto',
            new_name='peso_volumen_producto',
        ),
        migrations.RenameField(
            model_name='panaderiaypasteleria',
            old_name='peso_producto',
            new_name='peso_volumen_producto',
        ),
        migrations.RenameField(
            model_name='quesoyfiambres',
            old_name='peso_producto',
            new_name='peso_volumen_producto',
        ),
        migrations.RenameField(
            model_name='refrigerados',
            old_name='peso_producto',
            new_name='peso_volumen_producto',
        ),
        migrations.RenameField(
            model_name='verdurasyfrutas',
            old_name='peso_producto',
            new_name='peso_volumen_producto',
        ),
        migrations.AddField(
            model_name='bebesyniños',
            name='tipo_unidad',
            field=models.CharField(choices=[('peso', 'Peso'), ('volumen', 'Volumen'), ('unidades', 'Unidades')], default='peso', max_length=9),
        ),
        migrations.AddField(
            model_name='bebesyniños',
            name='unidades_detalle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bebesyniños',
            name='unidades_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='bebidasylicores',
            name='tipo_unidad',
            field=models.CharField(choices=[('peso', 'Peso'), ('volumen', 'Volumen'), ('unidades', 'Unidades')], default='peso', max_length=9),
        ),
        migrations.AddField(
            model_name='bebidasylicores',
            name='unidades_detalle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bebidasylicores',
            name='unidades_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='carnes',
            name='tipo_unidad',
            field=models.CharField(choices=[('peso', 'Peso'), ('volumen', 'Volumen'), ('unidades', 'Unidades')], default='peso', max_length=9),
        ),
        migrations.AddField(
            model_name='carnes',
            name='unidades_detalle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carnes',
            name='unidades_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='congelados',
            name='tipo_unidad',
            field=models.CharField(choices=[('peso', 'Peso'), ('volumen', 'Volumen'), ('unidades', 'Unidades')], default='peso', max_length=9),
        ),
        migrations.AddField(
            model_name='congelados',
            name='unidades_detalle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='congelados',
            name='unidades_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='despensa',
            name='tipo_unidad',
            field=models.CharField(choices=[('peso', 'Peso'), ('volumen', 'Volumen'), ('unidades', 'Unidades')], default='peso', max_length=9),
        ),
        migrations.AddField(
            model_name='despensa',
            name='unidades_detalle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='despensa',
            name='unidades_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='ferreteria',
            name='tipo_unidad',
            field=models.CharField(choices=[('peso', 'Peso'), ('volumen', 'Volumen'), ('unidades', 'Unidades')], default='peso', max_length=9),
        ),
        migrations.AddField(
            model_name='ferreteria',
            name='unidades_detalle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ferreteria',
            name='unidades_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='limpieza',
            name='tipo_unidad',
            field=models.CharField(choices=[('peso', 'Peso'), ('volumen', 'Volumen'), ('unidades', 'Unidades')], default='peso', max_length=9),
        ),
        migrations.AddField(
            model_name='limpieza',
            name='unidades_detalle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='limpieza',
            name='unidades_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='mascotas',
            name='tipo_unidad',
            field=models.CharField(choices=[('peso', 'Peso'), ('volumen', 'Volumen'), ('unidades', 'Unidades')], default='peso', max_length=9),
        ),
        migrations.AddField(
            model_name='mascotas',
            name='unidades_detalle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mascotas',
            name='unidades_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='panaderiaypasteleria',
            name='tipo_unidad',
            field=models.CharField(choices=[('peso', 'Peso'), ('volumen', 'Volumen'), ('unidades', 'Unidades')], default='peso', max_length=9),
        ),
        migrations.AddField(
            model_name='panaderiaypasteleria',
            name='unidades_detalle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='panaderiaypasteleria',
            name='unidades_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='quesoyfiambres',
            name='tipo_unidad',
            field=models.CharField(choices=[('peso', 'Peso'), ('volumen', 'Volumen'), ('unidades', 'Unidades')], default='peso', max_length=9),
        ),
        migrations.AddField(
            model_name='quesoyfiambres',
            name='unidades_detalle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quesoyfiambres',
            name='unidades_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='refrigerados',
            name='tipo_unidad',
            field=models.CharField(choices=[('peso', 'Peso'), ('volumen', 'Volumen'), ('unidades', 'Unidades')], default='peso', max_length=9),
        ),
        migrations.AddField(
            model_name='refrigerados',
            name='unidades_detalle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='refrigerados',
            name='unidades_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='verdurasyfrutas',
            name='tipo_unidad',
            field=models.CharField(choices=[('peso', 'Peso'), ('volumen', 'Volumen'), ('unidades', 'Unidades')], default='peso', max_length=9),
        ),
        migrations.AddField(
            model_name='verdurasyfrutas',
            name='unidades_detalle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='verdurasyfrutas',
            name='unidades_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
